package validation

// knownUnsupportedIntent lists fixture cases whose expected result is not a
// function of the three input documents under the logical-item identity model.
// Each one encodes per-slot identity, or a network-attachment detach policy,
// that is not observable in oldbase/user/newbase: structurally identical
// inputs have different expected results, so no algorithm can satisfy both.
var knownUnsupportedIntent = map[string]struct{}{
	"set-list/service.network.aliases/pair/08-remote-delete__10-user-delete":                             {},
	"set-list/service.network.aliases/pair/08-remote-delete__14-user-delete-remote-modify":               {},
	"set-list/service.network.aliases/pair/10-user-delete__08-remote-delete":                             {},
	"set-list/service.network.aliases/pair/14-user-delete-remote-modify__08-remote-delete":               {},
	"set-list/service.network.link-local-ips/pair/08-remote-delete__10-user-delete":                      {},
	"set-list/service.network.link-local-ips/pair/08-remote-delete__14-user-delete-remote-modify":        {},
	"set-list/service.network.link-local-ips/pair/10-user-delete__08-remote-delete":                      {},
	"set-list/service.network.link-local-ips/pair/14-user-delete-remote-modify__08-remote-delete":        {},
	"unique-list/network.ipam.config/pair/02-remote-add__03-user-add":                                    {},
	"unique-list/network.ipam.config/pair/02-remote-add__04-both-add-same":                               {},
	"unique-list/network.ipam.config/pair/02-remote-add__05-both-add-different-user-wins":                {},
	"unique-list/network.ipam.config/pair/02-remote-add__09-user-modify":                                 {},
	"unique-list/network.ipam.config/pair/02-remote-add__10-user-delete":                                 {},
	"unique-list/network.ipam.config/pair/02-remote-add__11-both-modify-same":                            {},
	"unique-list/network.ipam.config/pair/02-remote-add__12-both-modify-different-user-wins":             {},
	"unique-list/network.ipam.config/pair/02-remote-add__13-user-modify-remote-delete":                   {},
	"unique-list/network.ipam.config/pair/02-remote-add__14-user-delete-remote-modify":                   {},
	"unique-list/network.ipam.config/pair/02-remote-add__15-both-delete":                                 {},
	"unique-list/network.ipam.config/pair/03-user-add__02-remote-add":                                    {},
	"unique-list/network.ipam.config/pair/03-user-add__07-remote-modify":                                 {},
	"unique-list/network.ipam.config/pair/03-user-add__08-remote-delete":                                 {},
	"unique-list/network.ipam.config/pair/04-both-add-same__07-remote-modify":                            {},
	"unique-list/network.ipam.config/pair/04-both-add-same__08-remote-delete":                            {},
	"unique-list/network.ipam.config/pair/04-both-add-same__10-user-delete":                              {},
	"unique-list/network.ipam.config/pair/04-both-add-same__14-user-delete-remote-modify":                {},
	"unique-list/network.ipam.config/pair/05-both-add-different-user-wins__07-remote-modify":             {},
	"unique-list/network.ipam.config/pair/05-both-add-different-user-wins__08-remote-delete":             {},
	"unique-list/network.ipam.config/pair/05-both-add-different-user-wins__10-user-delete":               {},
	"unique-list/network.ipam.config/pair/05-both-add-different-user-wins__14-user-delete-remote-modify": {},
	"unique-list/network.ipam.config/pair/08-remote-delete__04-both-add-same":                            {},
	"unique-list/network.ipam.config/pair/08-remote-delete__05-both-add-different-user-wins":             {},
	"unique-list/network.ipam.config/pair/08-remote-delete__09-user-modify":                              {},
	"unique-list/network.ipam.config/pair/08-remote-delete__10-user-delete":                              {},
	"unique-list/network.ipam.config/pair/08-remote-delete__11-both-modify-same":                         {},
	"unique-list/network.ipam.config/pair/08-remote-delete__12-both-modify-different-user-wins":          {},
	"unique-list/network.ipam.config/pair/08-remote-delete__14-user-delete-remote-modify":                {},
	"unique-list/network.ipam.config/pair/10-user-delete__04-both-add-same":                              {},
	"unique-list/network.ipam.config/pair/10-user-delete__05-both-add-different-user-wins":               {},
	"unique-list/network.ipam.config/pair/10-user-delete__07-remote-modify":                              {},
	"unique-list/network.ipam.config/pair/10-user-delete__08-remote-delete":                              {},
	"unique-list/network.ipam.config/pair/13-user-modify-remote-delete__02-remote-add":                   {},
	"unique-list/network.ipam.config/pair/13-user-modify-remote-delete__06-all-unchanged":                {},
	"unique-list/network.ipam.config/pair/13-user-modify-remote-delete__07-remote-modify":                {},
	"unique-list/network.ipam.config/pair/14-user-delete-remote-modify__04-both-add-same":                {},
	"unique-list/network.ipam.config/pair/14-user-delete-remote-modify__05-both-add-different-user-wins": {},
	"unique-list/network.ipam.config/pair/14-user-delete-remote-modify__07-remote-modify":                {},
	"unique-list/network.ipam.config/pair/14-user-delete-remote-modify__08-remote-delete":                {},
	"unique-list/network.ipam.config/pair/15-both-delete__02-remote-add":                                 {},
	"unique-list/network.ipam.config/pair/15-both-delete__07-remote-modify":                              {},
	"unique-list/network.ipam.config/pair/15-both-delete__08-remote-delete":                              {},
}
